In [1]:
%load_ext autoreload
%autoreload 2

import os
import seaborn as sns
from prfseeg import *

In [2]:
# laptop:
base_dir = '/Users/knapen/projects/prf-seeg/data'
# server:
# base_dir = '/scratch/2021/prf-seeg/data'

patient = Patient(subject='sub-001', 
                  raw_dir=os.path.join(base_dir, 'bids'), 
                  derivatives_dir=os.path.join(base_dir, 'derivatives'))
patient.gather_acquisitions()                  

Acquisition10kHz 1 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition10kHz 2 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition2kHz 3 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition2kHz 4 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition2kHz 5 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition2kHz 6 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-see

In [4]:
patient.find_electrode_positions(which_run=2)

Computing registration...
Using original zooms for translation ...
Optimizing translation:
    Optimizing level 2 [max iter: 10000]
    Optimizing level 1 [max iter: 1000]
    Optimizing level 0 [max iter: 100]
    Translation:  518.9 mm
    R²:             1.2%
Optimizing rigid:
    Optimizing level 2 [max iter: 10000]
    Optimizing level 1 [max iter: 1000]
    Optimizing level 0 [max iter: 100]
    Translation:    0.0 mm
    Rotation:      31.4°
    R²:             4.9%
Applying affine registration ...
[done]
Acquisition10kHz 1 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition10kHz 2 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg/data/derivatives on task pRF created.
Acquisition2kHz 3 for Patient "sub-001" at "/Users/knapen/projects/prf-seeg/data/bids", derivatives at /Users/knapen/projects/prf-seeg

ImageFileError: Filespec "/Users/knapen/projects/prf-seeg/data/derivatives/prep/sub-001/loc/CT2T1w.nii.gz" does not look right for class <class 'nibabel.spatialimages.SpatialImage'>

In [12]:
gui = mne.gui.locate_ieeg(patient.acquisitions[2].raw.info,
                                  patient.subj_trans,
                                  patient.CT_aligned,
                                  subject=patient.subject,
                                  subjects_dir=patient.subjects_dir)

/var/folders/sd/kggdbsc53wl2lptrqmw5wyk40000gn/T/ipykernel_10819/3863844628.py:1: RuntimeWarning: `seghead` not found, skipping head plot, see :ref:`mne.bem.make_scalp_surfaces` to add the head
  gui = mne.gui.locate_ieeg(patient.acquisitions[2].raw.info,


Using pyvistaqt 3d backend.



qt.qpa.window: <QNSWindow: 0x7feffa31a150; contentView=<QNSView: 0x7ff1350fd560; QCocoaWindow(0x7ff1350f81d0, window=QWidgetWindow(0x7ff135270cf0, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
qt.qpa.window: <QNSWindow: 0x7feff5633ed0; contentView=<QNSView: 0x7feff564c330; QCocoaWindow(0x7feff564cbd0, window=QWidgetWindow(0x7feff5640d60, name="QWidgetClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.


Clicked axis 2 at pos (162.55555555555554, 140.63797468354431)
Clicked axis 1 at pos (142.71555555555554, 105.66666666666666)
Clicked axis 0 at pos (169.08241912798874, 120.77777777777777)
Clicked axis 1 at pos (138.87555555555554, 124.33333333333331)
Clicked axis 1 at pos (136.31555555555553, 124.33333333333331)
Clicked axis 1 at pos (138.23555555555555, 126.2222222222222)
Clicked axis 2 at pos (172.0133333333333, 72.57301247096996)
Clicked axis 0 at pos (64.57301247096996, 135.88888888888886)
Clicked axis 2 at pos (158.79111111111106, 132.92612390367614)
Clicked axis 2 at pos (173.90222222222218, 65.31396760845183)
Clicked axis 2 at pos (158.7911111111111, 132.9261239036761)
Clicked axis 1 at pos (167.47285024154587, 105.66666666666664)
Clicked axis 2 at pos (127.47285024154588, 51.60629756503648)
Clicked axis 2 at pos (171.91729468599027, 67.722071805268)
Clicked axis 0 at pos (139.72207180526797, 107.44444444444441)
Clicked axis 2 at pos (145.2506280193236, 143.241608708307)
Clicke

In [11]:
patient.CT_aligned.to_file_map?

Signature: patient.CT_aligned.to_file_map(file_map=None)
Docstring: <no docstring>
File:      ~/software/anaconda3/envs/py39/lib/python3.9/site-packages/nibabel/filebasedimages.py
Type:      method


In [13]:
patient.subj_trans

<Transform | head->MRI (surface RAS)>
[[ 0.99442248 -0.09683619 -0.04179336  0.00826246]
 [ 0.09032022  0.98649145 -0.13666336 -0.00354597]
 [ 0.05446275  0.13212633  0.98973554 -0.04298648]
 [ 0.          0.          0.          1.        ]]